defaults:
  db_url: postgresql+psycopg://user:pass@localhost:5432/ingest_db
  batch_size: 5000
  on_conflict: upsert           # options: append | upsert | fail
  commit_freq_type: insert   # options: insert | row
  commit_freq : 1 #options: any non-negative int. 0 means only commits when everything is done. risky

sources:
  - name: drug_product
    type: csv
    path: data/Drugs_product.csv
    schemas:
      - schema:
          name : drug_product
          target_table: drug_table
          pk: [PRODUCTID]
          attributes:
            PRODUCTID : str
            PRODUCTNDC : str
            PRODUCTTYPENAME: str
            PROPRIETARYNAME: str
            PROPRIETARYNAMESUFFIX: str
            DEASCHEDULE : str
          rules:
            - PRODUCTNDC: NOT NULL
            - PROPRIETARYNAME: NOT NULL
            - PRODUCTTYPENAME: NOT NULL
      - schema:
          name : drug_class
          target_table: drug_classes
          pk: [PRODUCTID,PHARM_CLASS]
          attributes:
            PHARM_CLASS : str
            PRODUCTID : str
          attr_name_map:
            PHARM_CLASS : PHARM_CLASSES
          rules:
            - PRODUCTID : REFERENCES drug_table(PRODUCTID)
      - schema:
          name : drug_substance
          target_table : drug_substances
          pk: [ PRODUCTID,SUBSTANCENAME ]
          attributes:
            SUBSTANCENAME: str
            PRODUCTID: str
          rules:
            - PRODUCTID: REFERENCES drug_table(PRODUCTID)
      - schema:
          name : drug_administration
          target_table: drug_administration_method
          pk: [ PRODUCTID,DOSAGEFORMNAME,ROUTENAME ]
          attributes:
            DOSAGEFORMNAME: str
            ROUTENAME: str
            PRODUCTID: str
          rules:
            - PRODUCTID: REFERENCES drug_table(PRODUCTID)
      - schema:
          name : drug_units
          target_table: drug_administration_units
          pk: [ PRODUCTID,STRENGTH,UNIT]
          attributes:
            STRENGTH: float
            UNIT: str
            PRODUCTID: str
          attr_name_map:
            STRENGTH : ACTIVE_NUMERATOR_STRENGTH
            UNIT : ACTIVE_INGRED_UNIT
          rules:
            - PRODUCTID: REFERENCES drug_table(PRODUCTID)
          links:
            -STRENGTH : UNIT
      - schema:
          name: drug_alias
          target_table: drug_alias
          pk: [ PRODUCTID,NONPROPRIETARYNAME ]
          attributes:
            NONPROPRIETARYNAME : str
            PRODUCTID: str
          rules:
            - PRODUCTID: REFERENCES drug_table(PRODUCTID)
      - schema:
          name : drug_company
          target_table: drug_company
          pk: [ APPLICATIONNUMBER,STARTMARKETINGDATE]
          attributes:
            STARTMARKETINGDATE: date
            ENDMARKETINGDATE: date
            MARKETINGCATEGORYNAME: str
            APPLICATIONNUMBER: str
            LABELERNAME: str
            PRODUCTID: str
          rules:
            - PRODUCTID:  REFERENCES drug_table(PRODUCTID)
            - STARTMARKETINGDATE: NOT NULL
            - APPLICATIONNUMBER : NOT NULL
            - LABELERNAME: NOT NULL
    data_types:
      PRODUCTID: str
      PRODUCTNDC : str
      PRODUCTTYPENAME: str
      PROPRIETARYNAME: str
      PROPRIETARYNAMESUFFIX : str
      NONPROPRIETARYNAME : str
      DOSAGEFORMNAME: str
      ROUTENAME : str[]
      STARTMARKETINGDATE : date
      ENDMARKETINGDATE : date
      MARKETINGCATEGORYNAME: str
      APPLICATIONNUMBER : str
      LABELERNAME : str
      SUBSTANCENAME : str[]
      ACTIVE_NUMERATOR_STRENGTH : float[]
      ACTIVE_INGRED_UNIT : str[]
      PHARM_CLASSES : str[]
      DEASCHEDULE : str
  - name: drug_effects
    type: json
    path: data/medical_medicine_dataset.jsonl
    schemas:
      - schema:
          name: drug_uses
          target_table: drug_uses
          pk: [ medicine_name, use ]
          attributes:
            medicine_name: str
            use: str
          attr_name_map:
            use: uses
          rules:
      - schema:
          name: drug_side_effects
          target_table: drug_side_effects
          pk: [ medicine_name, side_effect]
          attributes:
            medicine_name : str
            side_effect : str
          attr_name_map:
            side_effect: side_effects
          rules:
    data_types:
      id: int
      medicine_name: str
      description: str
      uses: str[]
      side_effects: str[]
      disclaimer: str

